version: '3.8'
services:
  app:
    image: {{ACR_LOGIN_SERVER}}/fastapi-app:{{IMAGE_TAG}}
    container_name: fastapi-app
    restart: unless-stopped
    ports:
      - "8000:8000"

  nginx:
    image: {{ACR_LOGIN_SERVER}}/nginx-proxy:{{IMAGE_TAG}}
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - app
