version: '3.8'

services:
  app:
    build: ./app
    container_name: fastapi-app
    restart: unless-stopped


  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
