version: '3.8'

services:
  app:
    build: .
    container_name: fastapi-app
    restart: unless-stopped
    ports:
      - "8000:8000"


  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
