name: ci pipeline

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: pytest

    - name: 'Notify Telex of Test Success'
      if: success()
      run: |
        curl -X POST \
          ${{ secrets.TELEX_WEBHOOK }} \
          -H "accept: application/json" \
          -H "Content-Type: application/json" \
          -d '{
            "event_name": "ci-pipline",
            "message": "✅ Test passed for PR ${{ github.event.pull_request.number }}",
            "status": "success",
            "username": "Github Actions"
          }'
    - name: 'Notify Telex of Test Failure'
      if: failure()
      run: |
        curl -X POST \
          "https://ping.telex.im/v1/webhooks/019509c2-bfe1-758f-8535-6f9accdeb20a" \
          -H "accept: application/json" \
          -H "Content-Type: application/json" \
          -d '{
            "event_name": "ci-pipline",
            "message": "❌ Test failed for PR ${{ github.event.pull_request.number }}",
            "status": "failure",
            "username": "Github Actions"
          }'
