name: cd pipline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
          login-server: ${{ secrets.AZURE_ACR_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}

    - name: Build and Push Docker Image to ACR
      run: |
        IMAGE_TAG=${GITHUB_SHA}
        docker build --no-cache -t ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/fastapi-app:${IMAGE_TAG} .
        docker push ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/fastapi-app:${IMAGE_TAG}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: "hngfastapi"
        slot-name: "production"
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: "hngfastapi.azurecr.io/fastapi-app:${{ github.sha }}"

    - name: Update Nginx Config
      uses: azure/webapps-deploy@v2
      with:
        app-name: "hngfastapi"
        slot-name: "production"
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./nginx.conf
        startup-command: |
          cp /home/site/wwwroot/nginx.conf /etc/nginx/conf.d/default.conf
          nginx -s reload


