name: cd pipline
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
          login-server: ${{ secrets.AZURE_ACR_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}
    - name: Build and Push Images
      run: |
        IMAGE_TAG=${GITHUB_SHA}
        # Build and push FastAPI app
        docker build --no-cache -t ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/fastapi-app:${IMAGE_TAG} .
        docker push ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/fastapi-app:${IMAGE_TAG}
        # Build and push Nginx with config
        docker build -f nginx.Dockerfile -t ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/nginx:${IMAGE_TAG} .
        docker push ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/nginx:${IMAGE_TAG}
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: "hngfastapi"
        slot-name: "production"
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: |
          ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/fastapi-app:${{ github.sha }}
          ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/nginx:${{ github.sha }}